# -*- coding: utf-8 -*-
"""odev1_istiklal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Ds9pBsD9LZQJSc05gewM5INe_h70sdY
"""

def split_text(text,n):
  
  kitalar = {}
 # keys = range(n)
  
  text_list = text.split('\n\n')
  
  x=0
  
  while x < len(text_list):
     
    text_list[x].strip("\n")
    
    x+=1
  
  kitalar = { i : text_list[i] for i in range(0, len(text_list) ) }
  
  return kitalar.get(n-1)
  
 

  

istiklal = """Korkma, sönmez bu şafaklarda yüzen al sancak; 
            Sönmeden yurdumun üstünde tüten en son ocak. 
            O benim milletimin yıldızıdır, parlayacak; 
            O benimdir, o benim milletimindir ancak.

            Çatma, kurban olayım, çehreni ey nazlı hilâl! 
            Kahraman ırkıma bir gül! Ne bu şiddet, bu celâl? 
            Sana olmaz dökülen kanlarımız sonra helâl... 
            Hakkıdır, Hakk’a tapan, milletimin istiklâl! 

            Ben ezelden beridir hür yaşadım, hür yaşarım. 
            Hangi çılgın bana zincir vuracakmış? Şaşarım! 
            Kükremiş sel gibiyim, bendimi çiğner, aşarım. 
            Yırtarım dağları, enginlere sığmam, taşarım. 

            Garbın afakını sarmışsa çelik zırhlı duvar, 
            Benim iman dolu göğsüm gibi serhaddım var. 
            Ulusun, korkma! Nasıl böyle bir imanı boğar, 
            “Medeniyet!” dediğin tek dişi kalmış canavar? 

            Arkadaş! Yurduma alçakları uğratma, sakın. 
            Siper et gövdeni, dursun bu hayâsızca akın 
            Doğacaktır sana va’dettiği günler Hakk’ın... 
            Kim bilir, belki yarın, belki yarından da yakın. 

            Bastığın yerleri “toprak!” diyerek geçme, tanı: 
            Düşün altındaki binlerce kefensiz yatanı. 
            Sen şehit oğlusun, incitme, yazıktır, atanı: 
            Verme, dünyaları alsan da, bu cennet vatanı. 

            Kim bu cennet vatanın uğruna olmaz ki feda? 
            Şüheda fışkıracak toprağı sıksan, şüheda!
            Canı, cananı, bütün varımı alsın da Huda, 
            Etmesin tek vatanımdan beni dünyada cüda.

            Ruhumun senden, İlâhî, şudur ancak emeli: 
            Değmesin mabedimin göğsüne namahrem eli. 
            Bu ezanlar ki şahadetleri dinin temeli- 
            Ebedî yurdumun üstünde benim inlemeli. 

            O zaman vecd ile bin secde eder-varsa-taşım,
            Her cerihamdan, ilâhî, boşanıp kanlı yaşım, 
            Fışkırır ruh-ı mücerret gibi yerden naşım; 
            O zaman yükselerek arşa değer belki başım. 

            Dalgalan sen de şafaklar gibi ey şanlı hilâl! 
            Olsun artık dökülen kanlarımın hepsi helâl. 
            Ebediyen sana yok, ırkıma yok izmihlâl:
            Hakkıdır, hür yaşamış, bayrağımın hürriyet;
            Hakkıdır, Hakk’a tapan, milletimin istiklâl"""



n=int(input("misra numarası gir: "))

print(split_text(istiklal,n))

#text_list =istiklal.split('\n\n')
  
#print(text_list[n-1])